#PBS -N distributed-relaxation
#PBS -S /bin/bash

## Specify the resources: one node with 8 cores and for 1 hour (DD:HH:MM:SS)
## nodes
#PBS -l nodes=4:ppn=8
#PBS -l walltime=0:15:00
#PBS -A cm30225
#PBS -e err.log
#PBS -o out.log

# Mail to user when job terminate or abort (b=begins, e=ends, a=aborts)
#PBS -m ae
echo $0
echo $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
module load gcc torque
make clean
make
OUTPUT=tests.log
echo "Timing 4090x4090"
(time mpirun -n 32 relax -n 4090)  2>&1 > /dev/null | grep real | awk '{print $2}'|sed "s/^[0-9]\+m//" | xargs printf "32\t%s\n" >> $OUTPUT
(time mpirun -n 16 relax -n 4090)  2>&1 > /dev/null | grep real | awk '{print $2}'|sed "s/^[0-9]\+m//" | xargs printf "16\t%s\n" >> $OUTPUT
(time mpirun -n 32 relax -n 4090)  2>&1 > /dev/null | grep real | awk '{print $2}'|sed "s/^[0-9]\+m//" | xargs printf "8\t%s\n" >> $OUTPUT
#./time.sh
